### ISSUE TITLE
Portal issues

### ISSUE THREAD

**Issue by Flameminer221** [DivineRPG/DivineRPG#177]
When you use the /divinerpg {dimension} command, it may spawn you directly in the portal back to the Overworld, which makes it hard to enter some dimensions with said command.

This also occurs with my Nightmare Bed, which is probably a more serious issue since it can make Vethea almost impossible to enter on Survival. Could this be because the Nightmare Bed does not use normal portal mechanics and just drops you in the dimension like the /divinerpg command?

**Comment by Eternaldoom** [comment]
The command is going to be removed. I haven't noticed that with the bed though.

**Comment by aking4125** [comment]
The bed seems to be inconsistent for me too. At one point it works fine. Once I try to return, sometimes I spawn near world origin way deep underground with just the portal there. The portal doesn't work in the overworld. I tend to spawn inside the portal block and suffocate. This happens when I then return to Vethea, if I make a wrong move I go through the portal and teleport back. It tends to not happen all the time. I'm sure the portal is temporary or something.

**Comment by Eternaldoom** [comment]
It's not temporary. I'll look into this.
