### ISSUE TITLE
Broken day night cycle in the dimensions

### ISSUE THREAD

**Issue by DiamondWalker** [DivineRPG/DivineRPG#394]
Happens in twilight dimensions. Unsure if it happens anywhere else. In the dimensions there's a day-night cycle, even though there isn't a sun or moon, which makes them look really weird.

**Comment by velocityraptor-real** [comment]
the day and night cycle is intended.
It is there to fix shader compatibility issues.
You can close this issue report.

**Comment by Cruuk** [comment]
> 
> 
> the day and night cycle is intended.
> It is there to fix shader compatibility issues.
> You can close this issue report.

Trying to design around shaders- bloatware that people use to show off their powerful PCs, is an unacceptable design choice. I don't think Diamond will be satisfied for that reason.

**Comment by velocityraptor-real** [comment]
You are now bringing up the meaning of shaders, and I totally disagree with your statement:
Shaders are NOT to show off a powerful pc.
Of course there are people misusing them to show their powerful pcs, but theese people are totally unrelevant to the reason why the compatibility exists.
This compat fix exists for players enjoying the shader/playing with the shader in a regular basis.
Also: the compat fix works almost only for the SEUS-Renewed shader, so showing off a newer and more GPU-intensive shader would most likeley not even work.
And why would any person whant to show off their pc in the divineRPG mod?
As I said: This compat exists for player-game-(beautifullness)-enjoyment.

**Comment by Cruuk** [comment]
> 
> 
> You are now bringing up the meaning of shaders, and I totally disagree with your statement:
> Shaders are NOT to show off a powerful pc.
> Of course there are people misusing them to show their powerful pcs, but theese people are totally unrelevant to the reason why the compatibility exists.
> This compat fix exists for players enjoying the shader/playing with the shader in a regular basis.
> Also: the compat fix works almost only for the SEUS-Renewed shader, so showing off a newer and more GPU-intensive shader would most likeley not even work.
> And why would any person whant to show off their pc in the divineRPG mod?
> As I said: This compat exists for player-game-(beautifullness)-enjoyment.

I would evaluate the amount of players this would benefit. Realistically, I don't think a majority of Minecraft players use Shaders, and when you also measure how many players can run Shaders while getting consistent FPS, the number really begins to shrink. Yes? Of course, beauty is subjective, but I think leaving the vanilla day/night system in a very non-vanilla dimension, for such a specific reason- is a bit odd.

Furthermore, This is only compatible with "SEUS-Renewed shader" and no other shader? Remember what I asked earlier, who does this benefit. I imagine that the amount of players who can reliably use this SEUS-Renewed shader are small in numbers. Under normal circumstances, I personally don't really care how the Twilight dims look with the vanilla day/night cycle (Wildwood looked a little cool, but I don't use Shaders), but if they've been deliberately kept this way for 1 shader, then that seems silly and unnecessary. In the end, I do not see how this would benefit the DRPG community and the mod as a whole.

**Comment by velocityraptor-real** [comment]
You are right and this does not benefit the community almost at all, but this compatibility is no harm for regular players.
I know that some people would maybe prefer the old style of how the twighlight time works, but for players like me (using SEUS in a regular basis and had real visual problems in 1.7.10 divineRPG) the switch back to old style time would greatly harm my game expierience.
The only solution that satisfies both would be to keep the sun static. (I think eden has this rn)
(also, its more of a series of shaders rather than 1 shader and sildur's shaders also kinda work)

**Comment by DiamondWalker** [comment]
I agree with cruuk. Although it is nice that the dimensions work with shaders, including an odd, nonexistant sun for all players just because of the small community of shader users is a strange decision. At the very least this should be a config option or something. As for no harm, I feel like this really breaks the immersion, almost as much as the issues that result from using shaders in dimensions without a day-night cycle. At first glance it also looks like a bug which gives new players a bad first impression.

I'd also like to mention that shaders break in almost all dimension mods, and sometimes in vanilla as well, so I feel like the shaders are at fault here.

**Comment by AstralScourge** [comment]
Just want to clear something up. This entire discussion is based off of false premises; the day-night cycle was a result of a copy-pasted world provider and had nothing to do with any shaders (not sure where that reasoning came from). Furthermore, the shader that was supposedly broken to cause the change was only ever tested in 1.7.10, and there's no proof that it'd be broken in 1.12.2. If it was broken, it would most likely be on their end and no compatibility change would be made simply for one single specific broken shader.

I'll probably remove the day-night cycle because the dimensions, as hard as it is to find a purpose for them, do kind of somewhat represent a progression in time at the moment and day-night is kind of pointless for them as is.

**Comment by AstralScourge** [comment]
Fixed in 7257f1b
