### ISSUE TITLE
[1.19.2] Mobs not spawning/Mob spawn rate too low

### ISSUE THREAD

**Issue by vibrantmess** [DivineRPG/DivineRPG#645]
### Mobs not spawning/Mob spawn rate too low

Minecraft 1.19.2 Forge 43.3.0, but I think this is true for all versions. I remember playing Divine RPG 10 years ago and having issues with mob spawning in Overworld, seems that the issue still persists.
I have a lot of mods installed that adding additional mobs, all of them are working fine, only Divine RPG mobs are almost not spawning.

I've thought that William Wythers' Expanded Ecosphere was messing with biomes, but after I removed the mod nothing changed.

Is there a possible conflict between mob IDs between different mods?

**Comment by velocityraptor-real** [comment]
mob id conflicts do usually not happen in modern minecraft versions. Our mob spawn criteria have changed since old minecraft versions, so some mobs might be a bit rarer or more biome specific. as the overworld terrain changedin 1.18 there is now also way more hidden terrain where mobs could spawn, which lowers the probability of encountering a mob.

**Comment by Necumate** [comment]
Is it possible to make Enthralled Dramcryx to spawn regardless the type of cave?
I have same issue where's 4 worldgen mod installed (Regions Unexplored, terralith+tectonic, biomes o plenty), so it's significally reduce spawnrate. Unfortunately, i can't get how to use Incontrol
