### ISSUE TITLE
Alleged server crash caused by Inferno Bow

### ISSUE THREAD

**Issue by Rattle189** [DivineRPG/DivineRPG#674]
The server crashed sometime in the morning because someone said they used an Inferno Bow against a mob from another mod called Born in Chaos.

[crash-2024-09-15_03.03.27-server.txt](https://github.com/user-attachments/files/17004478/crash-2024-09-15_03.03.27-server.txt)

**Comment by NicosaurusRex99** [comment]
i notice a few things with that crash.
1. Born in chaos is a MCreator mod which tend to not play so well on servers 
2. you are using DivineRPG Version: 1.10.7.3, Please try using 1.10.7.5 
3. This is most likely due to the mcreator mod but also passive skill tree was mentioned so it could be any 1 of those 3 mods but id start with the mcreator one

**Comment by Rattle189** [comment]
I updated to 1.10.7.5 first and there has been no problems so far. They were able to use the bows and use them against the monsters from the Born in Chaos mod. I'll close this for now and re-open it if another issue occurs.
